
services:
  # خدمة MongoDB
  mongo:
    image: mongo:6.0.26-nanoserver
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    restart: always

  # خدمة Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1

    restart: always

  # خدمة WebSocket_Candle
  websocket_candle:
    build: .
    container_name: websocket_candle
    command: python3 WebSocket_Candle.py
    depends_on:
      - redis
      - mongo
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  # خدمة Strategy_Engine
  strategy_engine:
    build: .
    container_name: strategy_engine
    command: python3 Strategy_Engine.py
    depends_on:
      - redis
      - mongo
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  mongo_data:
