
services:
  Websocket_Candle:
    build:
      context: .
    container_name: Websocket_Candle
    environment:
      - SCRIPT_NAME=Websocket_Candle.py
      - MONGO_HOST=mongodb
      - REDIS_HOST=redis
    volumes:
      - .:/app
    restart: always
    depends_on:
      - mongodb
      - redis

  Strategy_Engine:
    build:
      context: .
    container_name: Strategy_Engine
    environment:
      - SCRIPT_NAME=Strategy_Engine.py
      - MONGO_HOST=mongodb
      - REDIS_HOST=redis
    volumes:
      - .:/app
    restart: always
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:noble
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
