version: "3.9"
services:
  trading_bot:
    build: .
    container_name: trading_system
    command: python3 WebSocket_Real_time.py
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
