name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/server_key.pem
          chmod 600 ~/.ssh/server_key.pem
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on Server
        run: |
          ssh -i ~/.ssh/server_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/Trading_system
            echo "Resetting repo..."
            git reset --hard HEAD
            git clean -fd
            echo "Pulling latest code..."
            git pull origin main
            echo "Stopping and removing all containers..."
            docker stop $(docker ps -aq) || true
            docker rm -f $(docker ps -aq) || true
            echo "Removing all images..."
            docker rmi -f $(docker images -q) || true
            echo "Rebuilding and restarting containers..."
            docker-compose up -d --build
          EOF
