name: Run Trading System

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 2️⃣ SSH إلى السيرفر لتنفيذ الأوامر
      - name: Deploy to Debian server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: admin
          key: ${{ secrets.AWS_PEM_KEY }}
          script: |
            cd ~/trading_system
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            docker compose down --remove-orphans
            docker compose up -d --build

